FROM node:20-bookworm as build

ARG JWT_SECRET
ARG DATABASE_URL
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASS
ARG REDIS_USER
ARG GATEWAY_ASAAS_TOKEN
ARG GATEWAY_ASAAS_BASE_URL

ENV JWT_SECRET=${JWT_SECRET}
ENV DATABASE_URL=${DATABASE_URL}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV REDIS_PASS=${REDIS_PASS}
ENV REDIS_USER=${REDIS_USER}
ENV GATEWAY_ASAAS_TOKEN=${GATEWAY_ASAAS_TOKEN}
ENV GATEWAY_ASAAS_BASE_URL=${GATEWAY_ASAAS_BASE_URL}

WORKDIR /app
COPY package*.json ./
RUN npm config set loglevel verbose
RUN pnpm install
COPY . .
RUN pnpm deploy:migrate && pnpm build

WORKDIR /app
COPY --from=build /app ./

EXPOSE 8000
CMD ["npm", "start"]