FROM node:20-bookworm AS build

WORKDIR /app
COPY package*.json ./
RUN npm config set loglevel verbose
RUN npm install

COPY . .
RUN npm run build

FROM node:20-bookworm AS production

WORKDIR /app
COPY --from=build /app ./

EXPOSE 8080
CMD ["node", "dist/scheduler.js"]